version: '3.5'
services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=400'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api01:
    image: rinhadotnet
    hostname: rinhadotnet-api01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;MaxPoolSize=200
      - ASPNETCORE_URLS=http://+:80;http://+:81
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
  api02:
    image: rinhadotnet
    hostname: rinhadotnet-api02
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;MaxPoolSize=200
      - ASPNETCORE_URLS=http://+:80;http://+:81
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  default:
    driver: bridge
    name: rinhadotnet